### PR TITLE
Avoid gratuitous manual memory management and unnecessary top-level `QMainWindow`.

### PR DESCRIPTION
**Pull request by KubaO**

### CODE REVIEW

**Comment by jcelerier** [comment]
I must admit that I'm a bit torn on this. Of course, the code in this example is clearer. However, in actual Qt code you often end up allocating your objects on the heap and leave the ownership to Qt instead of having a "dual-ownership" between Qt and the stack. For instance if you have a widget : 

    struct MyWidget : public QWidget {
        MyWidget(QWidget* p): QWidget{p} {
            QPushButton s{this};  // won't work as expected
        }
    };

and you have instead to do 

    struct MyWidget : public QWidget {
        MyWidget(QWidget* p): QWidget{p} {
            new QPushButton{this};  // won't work as expected
        }
    };

or this, which causes endless pain if for some reason you want to reorder your widgets at runtime

    struct MyWidget : public QWidget {
        MyWidget(QWidget* p)
          : QWidget{p} 
          , m_button{this}
        {
        }

        QPushButton m_button;
    };

Do you think that this could be maybe in another file ? Or if you are convinced that this should be a "pretty-code" instead of "real code" showcase I can merge it.

**Comment by KubaO** [comment]
Child widgets that have same lifetime as the parent should be held by
value. That's how you write any modern C++ code. The `new` in the
constructor doesn't belong unless you're allocating a runtime-determined
number of them: in that case a `std::list<WidgetType>` is the container
that works for it - still, no explicit memory management.

I don't understand what's the point of other examples you propose. Of
course having `QPushbutton s{this}` has the extent of the constructor. It
belongs as a class member, not an automatic variable. Reordering widgets
within layouts is generally hard if that's what you refer to and layouts
don't really support it all that well, but if you need to do it you have to
destruct the widget and in-place construct its replacement. If you actually
want to do it, you'd want to factor it out into a helper function, so no
problem there: the use of that helper is no different between objects held
by value and indirectly by a pointer.

The layout and sub-widget(s) are held by value in the parent class. This
does not determine whether they are on the heap or on the stack. That
detail is determined by whoever constructs the instance of the **parent**
widget - `MyWidget`. In our case it's on the stack in the `main`, but that
doesn't have to be the case, and is irrelevant for lifetime management of
the sub-objects. If you wanted all those objects to live on the heap, you
could put `auto widget = std::make_unique<MyWidget>();` in `main()`. It
would change nothing much.

All that matters is that the `QObject` parent - the one whose `~QObject`
destructor deletes any remaining children - never gets to see those
children because it outlives them. By the time `~QObject` starts running,
the `~MyWidget` has returned and destroyed all member fields belonging to
it and there are no child objects held by value: they have been destroyed.
Thus the "double ownership" is a red herring: the semantics of C++ dictate
that no the `~QObject` will *never* manage those sub-objects - and that's
by design of the language.

The corollary is that in C++ the order of the members is important - it
newer was unimportant to begin with.

Qt examples are full of unnecessary dynamic memory allocations and
extraneous layers of indirection. They were never necessary even in C++98.

Cheers, Kuba

**Comment by jcelerier** [comment]
> Thus the "double ownership" is a red herring: the semantics of C++ dictate that no the `~QObject` will *never* manage those sub-objects - and that's by design of the language.

I disagree, it's terribly easy to get crashes due to this (that would not happen if only Qt had the ownership) :

    #include <QtWidgets>
    
    int main(int argc, char** argv)
    {
      QApplication app{argc, argv};
      QWidget widget;
      QHBoxLayout lay{&widget};
      QLabel label_1{"0", &widget};
      QPushButton pushbutton{"Count", &widget};
      QLabel label_2{"foo", &widget};
    
      uint32_t count{};
      QObject::connect(&pushbutton, &QPushButton::clicked,
          [&] () {
            label_1.setText(QString::number(++count));
            label_2.setText("clicked");
    
            // "Feature" added by an intern two months later
            pushbutton.setParent((count % 2) ? &label_2 : &label_1);
          });
    
      lay.addWidget(&label_1);
      lay.addWidget(&pushbutton);
      lay.addWidget(&label_2);
      widget.show();
      return app.exec();
    }

**Comment by KubaO** [comment]
What you propose is an intern who  doesn't understand the very basics of the language: order of destruction is a thing. Protecting against such silliness by adding one layer of indirection to all of the code is IMHO crazy. If you anticipate such people to work on the code, add a section to HACKING or README. Alas, feel free to disagree. I have well over 100k LOC of code now that's all written that way. It works fine.

**Comment by jcelerier** [comment]
> What you propose is an intern who doesn't understand the very basics of the language

Well, yes, but if you use stack allocation you have to keep in mind two different orders of destructions instead of one: the stack one and the qobject parent-child relationship ones. I don't doubt that you have no problem handling this mentally, but I remember a lot of late-night debugging sessions for either me or colleagues because that kind of thing isn't always evident.

**Comment by KubaO** [comment]
> On Feb 13, 2017, at 3:51 AM, Jean-Michaël Celerier <notifications@github.com> wrote:
> 
> What you propose is an intern who doesn't understand the very basics of the language
> 
> Well, yes, but if you use stack allocation you have to keep in mind two different orders of destructions instead of one: the stack one and the qobject parent-child relationship ones. I don't doubt that you have no problem handling this mentally, but I remember a lot of late-night debugging sessions for either me or colleagues because that kind of thing isn't always evident.

I see what you’re saying, but please forget the notion of this somehow applying to stack. It has got nothing to do with the stack, everything to do with value semantics. The following code has the same “problem", for the same reason, and **no** Qt objects live on the stack:

#include <QtWidgets>
#include <memory>

struct Foo {
  QLabel label1, label2, label3;
  explicit Foo(bool crash) {
    label2.setParent(crash ? &label3 : &label1);
  }
};

int main(int argc, char ** argv) {
  auto app = std::make_unique<QApplication>(argc, argv);
  auto foo = std::make_unique<Foo>(true);
}

When dealing with objects held by value, there is only one order of destruction mandated by C++, and you only have to make sure that Qt doesn’t try to do things out of order :)

Cheers, Kuba

**Comment by eugenkiss** [comment]
There seems to be no activity on this PR anymore. I'll close it for now.

**Pull request closed without merging**
