### PR TITLE
Add the Fyne toolkit to the implementations

### PR DESCRIPTION
**Pull request by Jacalz**
Fyne is a great toolkit for Go and the Go toolkit with the most starts on GitHub. Their site is https://fyne.io and the toolkit can be fount at https://github.com/fyne-io/fyne. This PR basically adds the work in progress implementation in to the website.

- [x] The website builds and works like it should.

### CODE REVIEW

**Comment by Jacalz** [comment]
@eugenkiss  Is there any chance that we possibly could see this merged? This has been open for a couple months now and it would be nice if we could get it over with :)

**Comment by dumblob** [comment]
@mirohs do you have permissions to transfer this repository to an organization (e.g. *UI and UX research*)?

I think an organization is a must now when there are numerous suggestions in the [issue tracker](https://github.com/eugenkiss/7guis/issues ) and PRs for quite some time, but @eugenkiss unfortunately [decided to not do anything further](https://medium.com/@eugenkiss/i-remember-having-read-the-paper-a-long-time-ago-1b74a35e5f ) with this while being inactive (and not responsive) for several years now.

I've tried to contact @eugenkiss in this regard few days ago through LinkedIn, but didn't get any answer. Therefore I'm asking you @mirohs to avoid hard fork. If you're in contact with @eugenkiss , could you please ask him?

**Comment by mirohs** [comment]
Dear dumblob,

would it be possible that we email or Skype about this?

Best,
Michael

**Comment by dumblob** [comment]
@mirohs sure, feel free to contact me on dumblob at gmail com

**Pull request merged**
