### PR TITLE
Implement the counter with Qt5

### PR DESCRIPTION
**Pull request by jcelerier**
There is also a CMakeLists.txt that could be easily used with other examples in Qt.

### CODE REVIEW

**Comment by eugenkiss** [comment]
Thanks for your contribution, @jcelerier ! I'm not familiar with Qt I must admit. What I see looks good though. I've added you as a collaborator so that you can push directly.

**Comment by jcelerier** [comment]
Thanks ! I did this to give a small sample of how it would look with Qt. I'll try to implement the others when I have time, and write a quick readme with build instructions / design philosophy.

**Comment by eugenkiss** [comment]
Cool! Looking forward to it :smile:.

**Comment by mirohs** [comment]
Hallo Herr Kiss,

schön, dass das aufgegriffen wird.

Viele Grüße,
Michael Rohs

**Pull request merged**
