### PR TITLE
Update Red implementation

### PR DESCRIPTION
**Pull request by greggirwin**

### CODE REVIEW

**Comment by eugenkiss** [comment]
@greggirwin Do you still intend to have this PR merged?

**Comment by eugenkiss** [comment]
Since the red implementation is already part of this repo with you being the author I'm open to merge this PR. Nonetheless, I'd be more happy if you'd be so kind to create a dedicated repo for the Red implementation of 7GUIs. See also https://eugenkiss.github.io/7guis/contributing/

**Comment by greggirwin** [comment]
@eugenkiss, I thought I did that for the PR originally, but I remember, too, that somehow it showed up as a single commit when you added it. My repo is at https://github.com/greggirwin/7guis.

**Comment by greggirwin** [comment]
It looks like the same PR, in redoing it just now. If you want, you could close this and I can do that again.

**Comment by eugenkiss** [comment]
@greggirwin sounds good, thanks. I'll close this PR then and wait for another.

Just to avoid confusion: What I suggested with "dedicated repo" was something like https://github.com/greggirwin/7guis-Red (hypothetical) similar to https://github.com/eugenkiss/7guis-Java7-Swing which will be linked from https://eugenkiss.github.io/7guis/implementations/. The source for the list is https://github.com/eugenkiss/7guis/blob/master/site/src/containers/Implementations.js#L150

**Comment by greggirwin** [comment]
Hi Eugen,

EK> @greggirwinsounds good, thanks. I'll close this PR then and wait for another.
EK>  Just to avoid confusion: What I suggested with "dedicated repo"
EK> was something like
EK> https://github.com/greggirwin/7guis-Red(hypothetical) similar to

Ah, just resubmitted then read this more carefully. I'm totally
slammed at the moment, so not sure I'll get re-org'd here right now.
Sorry about the confusion.

-- Gregg

**Comment by eugenkiss** [comment]
No worries, @greggirwin. There is no rush or anything like that. Please take your time. Thanks for being so responsive!

**Pull request closed without merging**
